from django.db import models
from django.utils import timezone
from SystemCode.models import BranchHolidayHandling,LoanHolidayHandling,BaseRateModule,InterestRateType
from SystemCode.models import InterestRateCategory
from Currency.models import TransactionCurrency
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Bank(models.Model):
    Id = models.CharField(max_length=10,primary_key=True)
    PHONE1 = models.CharField(max_length=300,blank=True)
    PHONE2 = models.CharField(max_length=300,blank=True)
    DEFAULTLANGUAGE = models.CharField(max_length=300,blank=True)
    BANKNAME = models.CharField(max_length=300,blank=True)
    PASSWORDLOCKOUTCOUNT = models.IntegerField(default=5)
    MOBILE = models.CharField(max_length=300,blank=True)
    ZIP = models.CharField(max_length=300,blank=True)
    WEBSITE = models.CharField(max_length=300,blank=True)
    COUNTRY = models.CharField(max_length=300,blank=True)
    CITY = models.CharField(max_length=300,blank=True)
    EMAIL = models.CharField(max_length=300,blank=True)
    ADDRESS = models.CharField(max_length=300,blank=True)
    SHORTNAME = models.CharField(max_length=300,blank=True)
    PASSWORDAGE =  models.IntegerField(default=30)
    LicenseKey = models.CharField(max_length=2000,blank=True)

class BankBranch(models.Model):
    BranchId = models.CharField(max_length=10,primary_key=True)
    BankId = models.ForeignKey(Bank, on_delete=models.CASCADE)
    ADDRESS =  models.CharField(max_length=300,blank=True)
    ADDRESS2 =  models.CharField(max_length=300,blank=True)
    ALLOWTRX = models.BooleanField(default=False)
    BASECURRENCY = models.ForeignKey(TransactionCurrency,on_delete=models.CASCADE)
    BRANCHCASHLIMIT = models.FloatField(blank=True, null=True)
    BRANCHCLOSEDDATE = models.DateTimeField(blank=True)
    BRANCHHOLIDAYSETTING = models.ForeignKey(BranchHolidayHandling,on_delete=models.CASCADE)
    BRANCHNAME =  models.CharField(max_length=300,blank=True)
    BRANCHOPENEDON = models.DateTimeField(blank=True)      
    BRANCHPREFIX =  models.CharField(max_length=300,blank=True)
    COBDATE = models.DateTimeField(blank=True) 
    CITY =  models.CharField(max_length=300,blank=True)
    COUNTRY =  models.CharField(max_length=300,blank=True)
    CREATEDBY = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    CREATEDON = models.DateField(default = timezone.now, blank=True ,null=True)
    EMAIL =  models.CharField(max_length=300,blank=True)
    EODDATE = models.DateTimeField(blank=True) 
    EOMDATE = models.DateTimeField(blank=True) 
    ENDYEAR = models.DateTimeField(blank=True) 
    FAX =  models.CharField(max_length=300,blank=True)       
    ISHEADOFFICE = models.BooleanField(default=False)        
    LOANHOLIDAYSETTING = models.ForeignKey(LoanHolidayHandling,on_delete=models.CASCADE)   
    MOBILE =  models.CharField(max_length=300,blank=True)  
    PHONE1 =  models.CharField(max_length=300,blank=True) 
    PHONE2 =  models.CharField(max_length=300,blank=True) 
    POBOX =  models.CharField(max_length=300,blank=True) 
    REGION =  models.CharField(max_length=300,blank=True) 
    SERAILID =  models.CharField(max_length=300,blank=True) 
    SHORTBRANCHNAME =  models.CharField(max_length=300,blank=True) 
    STARTYEAR = models.DateTimeField(blank=True)        
    ZIPCODE =  models.CharField(max_length=300,blank=True)       
    ISCLEARING = models.BooleanField(default=False)             
    SystemStartDate = models.DateField(default = timezone.now, blank=True ,null=True)    
    BranchLicenseKey = models.CharField(max_length=2000)
    Approved = models.BooleanField(default=False)
    UpdatedBy = models.CharField(max_length=2000)
    UpdatedOn = models.DateField(default = timezone.now, blank=True ,null=True)
    SupervisedBy = models.CharField(max_length=2000)
    SupervisedOn = models.DateField(default = timezone.now, blank=True ,null=True)
           
class BaseRate(models.Model):
    Id = models.BigAutoField(primary_key=True)
    ModuleType = models.ForeignKey(BaseRateModule,on_delete=models.CASCADE)
    CurrencyId = models.ForeignKey(TransactionCurrency,on_delete=models.CASCADE)
    BaseRate = models.FloatField(blank=True, null=True)
    EffectiveDate = models.DateField(default = timezone.now, blank=True ,null=True)
    UpdatedBy = models.CharField(max_length=2000)
    UpdatedOn = models.DateTimeField(default = timezone.now, blank=True ,null=True)
    SupervisedBy = models.CharField(max_length=2000,blank=True)
    SupervisedOn = models.DateTimeField(default = timezone.now, blank=True ,null=True)
    Checkers = models.IntegerField(default=0)
    IsSupervised = models.BooleanField(default=True)    

class InterestRate(models.Model):
    Id = models.BigAutoField(primary_key=True)
    RateName = models.CharField(max_length=2000,blank=True)
    RateType = models.ForeignKey(InterestRateType,on_delete=models.CASCADE)
    RateCategory = models.ForeignKey(InterestRateCategory,on_delete=models.CASCADE)
    CurrencyId = models.ForeignKey(TransactionCurrency,on_delete=models.CASCADE)
    EffectiveFromDate = models.DateTimeField(default = timezone.now, blank=True ,null=True)
    EffectiveToDate = models.DateTimeField(blank=True ,null=True)
    SlabWise = models.BooleanField(default=True) 
    Remarks = models.CharField(max_length=2000,blank=True) 
    UpdatedBy = models.CharField(max_length=2000)
    UpdatedOn = models.DateTimeField(default = timezone.now, blank=True ,null=True)
    SupervisedBy = models.CharField(max_length=2000,blank=True)
    SupervisedOn = models.DateField(default = timezone.now, blank=True ,null=True)
    Checkers = models.IntegerField(default=0)
    IsSupervised = models.BooleanField(default=True)  