# Generated by Django 5.0.14 on 2025-06-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCurrency",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("CURRENCYNAME", models.CharField(blank=True, max_length=300)),
                ("DESCRIPTION", models.CharField(blank=True, max_length=300)),
                ("ISO", models.CharField(blank=True, max_length=300)),
                ("MAXIMUMVALUE", models.FloatField()),
                ("MINIMUMVALUE", models.FloatField()),
                ("REMARKS", models.CharField(blank=True, max_length=300)),
                (
                    "CREATEDBY",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
