# Generated by Django 5.0.14 on 2025-05-09 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("SystemCode", "0003_currency_loanholidayhandling"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AMCEXPIRYDATE", models.CharField(blank=True, max_length=1000)),
                ("ADDRESS", models.CharField(blank=True, max_length=300)),
                ("ADDRESS2", models.CharField(blank=True, max_length=300)),
                ("ALLOWTRX", models.BooleanField(default=False)),
                ("BRANCHCASHLIMIT", models.FloatField(blank=True, null=True)),
                ("BRANCHCLOSEDDATE", models.DateTimeField(blank=True)),
                ("BRANCHNAME", models.CharField(blank=True, max_length=300)),
                ("BRANCHOPENEDON", models.DateTimeField(blank=True)),
                ("BRANCHPREFIX", models.CharField(blank=True, max_length=300)),
                ("COBDATE", models.DateTimeField(blank=True)),
                ("CITY", models.CharField(blank=True, max_length=300)),
                ("COUNTRY", models.CharField(blank=True, max_length=300)),
                (
                    "CREATEDON",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("EMAIL", models.CharField(blank=True, max_length=300)),
                ("EODDATE", models.DateTimeField(blank=True)),
                ("EOMDATE", models.DateTimeField(blank=True)),
                ("ENDYEAR", models.DateTimeField(blank=True)),
                ("FAX", models.CharField(blank=True, max_length=300)),
                ("ISHEADOFFICE", models.BooleanField(default=False)),
                ("MOBILE", models.CharField(blank=True, max_length=300)),
                ("PHONE1", models.CharField(blank=True, max_length=300)),
                ("PHONE2", models.CharField(blank=True, max_length=300)),
                ("POBOX", models.CharField(blank=True, max_length=300)),
                ("REGION", models.CharField(blank=True, max_length=300)),
                ("SERAILID", models.CharField(blank=True, max_length=300)),
                ("SHORTBRANCHNAME", models.CharField(blank=True, max_length=300)),
                ("STARTYEAR", models.DateTimeField(blank=True)),
                ("ZIPCODE", models.CharField(blank=True, max_length=300)),
                ("ISCLEARING", models.BooleanField(default=False)),
                (
                    "SystemStartDate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "BASECURRENCY",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.currency",
                    ),
                ),
                (
                    "BRANCHHOLIDAYSETTING",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.branchholidayhandling",
                    ),
                ),
                (
                    "CREATEDBY",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "LOANHOLIDAYSETTING",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.loanholidayhandling",
                    ),
                ),
            ],
        ),
    ]
