# Generated by Django 5.0.14 on 2025-06-25 12:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("PHONE1", models.CharField(blank=True, max_length=20)),
                ("PHONE2", models.CharField(blank=True, max_length=20)),
                ("DEFAULTLANGUAGE", models.CharField(blank=True, max_length=20)),
                ("BANKNAME", models.CharField(blank=True, max_length=20)),
                ("PASSWORDLOCKOUTCOUNT", models.IntegerField()),
                ("MAXIMUMPASSWORDAGE", models.IntegerField()),
                ("MOBILE", models.CharField(blank=True, max_length=20)),
                ("ZIP", models.CharField(blank=True, max_length=200)),
                ("WEBSITE", models.CharField(blank=True, max_length=200)),
                ("FAX", models.CharField(blank=True, max_length=200)),
                ("COUNTRY", models.CharField(blank=True, max_length=200)),
                ("CITY", models.CharField(blank=True, max_length=200)),
                ("EMAIL", models.CharField(blank=True, max_length=200)),
                ("ADDRESS", models.CharField(blank=True, max_length=200)),
                ("SHORTNAME", models.CharField(blank=True, max_length=200)),
                ("BankLicenseKey", models.CharField(max_length=2000)),
                ("Approved", models.BooleanField(default=False)),
                ("UpdatedBy", models.CharField(max_length=2000)),
                (
                    "UpdatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("SupervisedBy", models.CharField(max_length=2000)),
                (
                    "SupervisedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bankbranch",
            name="id",
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="Approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="BankId",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="BranchId",
            field=models.CharField(
                default=1, max_length=10, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="BranchLicenseKey",
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="SupervisedBy",
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="SupervisedOn",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="UpdatedBy",
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="UpdatedOn",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
