# Generated by Django 5.0.14 on 2025-06-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0002_bank_remove_bankbranch_id_bankbranch_approved_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
