# Generated by Django 5.0.14 on 2025-06-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0003_delete_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "Id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("PHONE1", models.CharField(blank=True, max_length=300)),
                ("PHONE2", models.CharField(blank=True, max_length=300)),
                ("DEFAULTLANGUAGE", models.CharField(blank=True, max_length=300)),
                ("BANKNAME", models.CharField(blank=True, max_length=300)),
                ("PASSWORDLOCKOUTCOUNT", models.IntegerField(default=5)),
                ("MOBILE", models.CharField(blank=True, max_length=300)),
                ("ZIP", models.CharField(blank=True, max_length=300)),
                ("WEBSITE", models.CharField(blank=True, max_length=300)),
                ("COUNTRY", models.CharField(blank=True, max_length=300)),
                ("CITY", models.CharField(blank=True, max_length=300)),
                ("EMAIL", models.CharField(blank=True, max_length=300)),
                ("ADDRESS", models.CharField(blank=True, max_length=300)),
                ("SHORTNAME", models.CharField(blank=True, max_length=300)),
                ("PASSWORDAGE", models.IntegerField(default=30)),
                ("LicenseKey", models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name="bankbranch",
            name="BankId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Bank.bank"
            ),
        ),
    ]
