# Generated by Django 5.0.14 on 2025-06-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0004_bank_alter_bankbranch_bankid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankbranch",
            name="AMCEXPIRYDATE",
        ),
    ]
