# Generated by Django 5.0.14 on 2025-06-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0005_remove_bankbranch_amcexpirydate"),
        ("Currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankbranch",
            name="BASECURRENCY",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Currency.transactioncurrency",
            ),
        ),
    ]
