# Generated by Django 5.0.14 on 2025-06-30 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0006_alter_bankbranch_basecurrency"),
        ("Currency", "0001_initial"),
        ("SystemCode", "0004_delete_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseRate",
            fields=[
                ("Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("BaseRate", models.FloatField(blank=True, null=True)),
                (
                    "EffectiveDate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("UpdatedBy", models.CharField(max_length=2000)),
                (
                    "UpdatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("SupervisedBy", models.CharField(max_length=2000)),
                (
                    "SupervisedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "CurrencyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Currency.transactioncurrency",
                    ),
                ),
                (
                    "ModuleType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.baseratemodule",
                    ),
                ),
            ],
        ),
    ]
