# Generated by Django 5.0.14 on 2025-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0007_baserate"),
    ]

    operations = [
        migrations.AddField(
            model_name="baserate",
            name="Checkers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="baserate",
            name="IsSupervised",
            field=models.BooleanField(default=True),
        ),
    ]
