# Generated by Django 5.0.14 on 2025-07-05 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0008_baserate_checkers_baserate_issupervised"),
        ("Currency", "0001_initial"),
        ("SystemCode", "0005_interestrateid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baserate",
            name="SupervisedBy",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                ("Id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "EffectiveFromDate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("EffectiveToDate", models.DateField(blank=True, null=True)),
                ("SlabWise", models.BooleanField(default=True)),
                ("Remarks", models.CharField(blank=True, max_length=2000)),
                ("UpdatedBy", models.CharField(max_length=2000)),
                (
                    "UpdatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("SupervisedBy", models.CharField(blank=True, max_length=2000)),
                (
                    "SupervisedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("Checkers", models.IntegerField(default=0)),
                ("IsSupervised", models.BooleanField(default=True)),
                (
                    "CurrencyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Currency.transactioncurrency",
                    ),
                ),
                (
                    "RateCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.interestratecategory",
                    ),
                ),
                (
                    "RateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.interestrateid",
                    ),
                ),
                (
                    "RateType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.interestratetype",
                    ),
                ),
            ],
        ),
    ]
