# Generated by Django 5.0.14 on 2025-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_alter_baserate_supervisedby_interestrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrate',
            name='RateId',
        ),
        migrations.AddField(
            model_name='interestrate',
            name='RateName',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
