# Generated by Django 5.0.14 on 2025-08-07 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_remove_interestrate_rateid_interestrate_ratename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserate',
            name='SupervisedOn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='baserate',
            name='UpdatedOn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='EffectiveFromDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='EffectiveToDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='UpdatedOn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
