# Generated by Django 5.0.14 on 2025-06-25 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Security", "0003_securityrole_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ModuleLicense", models.CharField(max_length=2000)),
                ("ModuleName", models.CharField(max_length=200)),
                ("ModuleDescription", models.CharField(default="", max_length=200)),
                ("ModuleTable", models.CharField(max_length=200)),
                ("IsConfigured", models.BooleanField(default=False)),
                ("HasView", models.BooleanField(default=False)),
                ("HasAdd", models.BooleanField(default=False)),
                ("HasEdit", models.BooleanField(default=False)),
                ("HasDelete", models.BooleanField(default=False)),
                ("HasSupervise", models.BooleanField(default=False)),
                ("HasMakerChecker", models.BooleanField(default=False)),
                ("HasWorkflow", models.BooleanField(default=False)),
                ("HasMaxValues", models.BooleanField(default=False)),
                ("HasCREDITPOSTINGLIMIT", models.BooleanField(default=False)),
                ("HasCREDITSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("HasDEBITPOSTINGLIMIT", models.BooleanField(default=False)),
                ("HasDEBITSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("HasEXCESSSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("DefaultNumRecords", models.IntegerField(default=200)),
                ("DefaultShowMineOnly", models.BooleanField(default=False)),
                ("ModuleGroup", models.CharField(default="", max_length=200)),
                ("ModuleView", models.CharField(default="", max_length=200)),
                ("IsMainModule", models.BooleanField(default=False)),
                ("ParentModuleId", models.CharField(default="", max_length=200)),
                ("IsSubModule", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleRight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("CanView", models.BooleanField(default=False)),
                ("CanAdd", models.BooleanField(default=False)),
                ("CanEdit", models.BooleanField(default=False)),
                ("CanDelete", models.BooleanField(default=False)),
                ("CanSupervise", models.BooleanField(default=False)),
                ("CanMakerChecker", models.BooleanField(default=False)),
                ("CanWorkflow", models.BooleanField(default=False)),
                ("CanMaxValues", models.BooleanField(default=False)),
                ("CREDITPOSTINGLIMIT", models.BooleanField(default=False)),
                ("CREDITSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("DEBITPOSTINGLIMIT", models.BooleanField(default=False)),
                ("DEBITSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("EXCESSSUPERVISIONLIMIT", models.BooleanField(default=False)),
                ("Approved", models.BooleanField(default=False)),
                (
                    "UpdatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("SupervisedBy", models.CharField(max_length=2000)),
                (
                    "SupervisedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "ModuleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemModule.mainmodule",
                    ),
                ),
                (
                    "UpdatedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Security.systemuser",
                    ),
                ),
                (
                    "UserRole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Security.securityrole",
                    ),
                ),
            ],
        ),
    ]
