# Generated by Django 5.0.14 on 2025-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemModule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmodule",
            name="DefaultNumRecords",
            field=models.IntegerField(default=10),
        ),
    ]
