# Generated by Django 5.0.14 on 2025-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemModule", "0002_alter_mainmodule_defaultnumrecords"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmodule",
            name="MenuName",
            field=models.CharField(default="", max_length=200),
        ),
    ]
