# Generated by Django 5.0.14 on 2025-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemModule", "0003_mainmodule_menuname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmodule",
            name="ParentModuleId",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
