# Generated by Django 5.0.14 on 2025-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemModule", "0004_alter_mainmodule_parentmoduleid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemControl",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ControlId", models.CharField(default="", max_length=200)),
                ("Details", models.CharField(max_length=200)),
            ],
        ),
    ]
