# Generated by Django 5.0.14 on 2025-06-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemModule", "0005_systemcontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemModuleConfigs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ColumnName", models.CharField(max_length=200)),
                ("ColumnType", models.CharField(max_length=200)),
                ("isMandatory", models.BooleanField(default=False)),
                ("QuestionCaption", models.CharField(default="", max_length=200)),
                ("isGridItem", models.BooleanField(default=False)),
                ("QuestionOrder", models.IntegerField(default=0)),
                ("GridOrder", models.IntegerField(default=0)),
                ("isSearchItem", models.BooleanField(default=False)),
                ("SearchProcedure", models.CharField(default="", max_length=200)),
                ("isUnique", models.BooleanField(default=False)),
                ("isAutoField", models.BooleanField(default=False)),
                ("FunctionEvent", models.CharField(default="", max_length=4000)),
                ("isLocked", models.BooleanField(default=False)),
                ("ControlType", models.CharField(default="", max_length=200)),
                (
                    "ModuleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemModule.mainmodule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemSubModuleConfigs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ColumnName", models.CharField(max_length=200)),
                ("ColumnType", models.CharField(max_length=200)),
                ("isMandatory", models.BooleanField(default=False)),
                ("QuestionCaption", models.CharField(default="", max_length=200)),
                ("isGridItem", models.BooleanField(default=False)),
                ("QuestionOrder", models.IntegerField(default=0)),
                ("GridOrder", models.IntegerField(default=0)),
                ("isSearchItem", models.BooleanField(default=False)),
                ("SearchProcedure", models.CharField(default="", max_length=200)),
                ("isUnique", models.BooleanField(default=False)),
                ("isAutoField", models.BooleanField(default=False)),
                ("FunctionEvent", models.CharField(default="", max_length=4000)),
                ("isLocked", models.BooleanField(default=False)),
                ("isCombo", models.BooleanField(default=False)),
                (
                    "SubModuleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemModule.mainmodule",
                    ),
                ),
            ],
        ),
    ]
