# Generated by Django 5.0.14 on 2025-08-07 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemModule', '0006_systemmoduleconfigs_systemsubmoduleconfigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodule',
            name='MakerCheckerLevels',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='MainModuleLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=2000)),
                ('BranchId', models.CharField(max_length=2000)),
                ('ActionId', models.CharField(max_length=2000)),
                ('JsonString', models.TextField(blank=True, null=True)),
                ('ModuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemModule.mainmodule')),
            ],
        ),
    ]
