# Generated by Django 5.0.14 on 2025-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemModule', '0007_mainmodule_makercheckerlevels_mainmodulelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodule',
            name='MakerCheckerLevels',
            field=models.IntegerField(default=2),
        ),
    ]
