# Generated by Django 5.0.14 on 2025-05-06 08:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("SystemCode", "0002_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "EndpointKey",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("Address", models.CharField(max_length=100)),
                ("SystemCode", models.CharField(max_length=100)),
                ("EndpointStatus", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("UserName", models.CharField(max_length=100)),
                ("UserEmail", models.CharField(max_length=100)),
                ("EmailConfirmed", models.BooleanField(default=False)),
                ("HashPassword", models.CharField(max_length=4000)),
                ("PhoneNumber", models.CharField(max_length=100)),
                ("OtpLogin", models.BooleanField(default=False)),
                ("Otp", models.CharField(blank=True, max_length=100)),
                ("AccessAllowed", models.BooleanField(default=False)),
                ("AccessLocked", models.BooleanField(default=False)),
                ("FirstName", models.CharField(max_length=100)),
                ("MiddleName", models.CharField(blank=True, max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("IDNumber", models.CharField(max_length=100)),
                (
                    "DOB",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "ResetDate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "CreatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("AccountActive", models.BooleanField(default=False)),
                (
                    "CreatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Sex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SystemCode.gender",
                    ),
                ),
            ],
        ),
    ]
