# Generated by Django 5.0.14 on 2025-05-09 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSession",
            fields=[
                ("KeyChain", models.BigAutoField(primary_key=True, serialize=False)),
                ("DataKey", models.IntegerField(blank=True, null=True)),
                ("ActiveKey", models.BooleanField(default=True)),
                (
                    "KeyDate",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "UserName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Security.systemuser",
                    ),
                ),
            ],
        ),
    ]
