# Generated by Django 5.0.14 on 2025-05-09 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0001_initial"),
        ("Security", "0002_systemsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("RoleName", models.CharField(max_length=200)),
                ("CreatedBy", models.CharField(blank=True, max_length=200)),
                (
                    "CreatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("ModifiedBy", models.CharField(blank=True, max_length=200)),
                (
                    "ModifiedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("ApprovedBy", models.CharField(blank=True, max_length=200)),
                (
                    "ApprovedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "DeactivatedBy",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "DeactivatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("CreatedBy", models.CharField(blank=True, max_length=200)),
                (
                    "CreatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("ModifiedBy", models.CharField(blank=True, max_length=200)),
                (
                    "ModifiedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("ApprovedBy", models.CharField(blank=True, max_length=200)),
                (
                    "ApprovedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "DeactivatedBy",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "DeactivatedOn",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "BranchId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank.bankbranch",
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Security.systemuser",
                    ),
                ),
                (
                    "UserRole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Security.securityrole",
                    ),
                ),
            ],
        ),
    ]
