# Generated by Django 5.0.14 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Security", "0003_securityrole_userrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="CreatedBy",
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
