# Generated by Django 5.0.14 on 2025-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Security", "0005_alter_systemuser_createdby_alter_userrole_createdby"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="ChangePassword",
            field=models.BooleanField(default=True),
        ),
    ]
