# Generated by Django 5.0.14 on 2025-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Security", "0007_alter_securityrole_createdby"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="SuperAdminUser",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
