# Generated by Django 5.0.14 on 2025-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountOperatingMode",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="AccountOperationMode",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="AgencyReportingPeriodType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="AssetAquisitionType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="BankProcess",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="BaseRateModule",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="BaseRateSpreadSign",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="BranchHolidayHandling",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ChargeFeeCalc",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CommisionPayableTo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CommisionShareOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CommisionSharingWith",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ContractState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CreditInterestCalcMethod",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CreditorDebit",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CreditTransactionDesc",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAccountState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DayCountBasis",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DebitInterestCalcMethod",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DebitTransactionDesc",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DenominationType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DepositCalculationType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentCopyorOriginal",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="EventNotificationConfig",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FDInterestApplicationFrequency",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FDRenewalMode",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FeeCalculatedOn",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FeeChargeEvent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FeePaymentModule",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FeeReceiptFormat",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FilterOperant",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FixedAssetDisposalType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FixedAssetRevaluationState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FixedAssetStatus",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FixedAssetTransferState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FixedInstallmentDay",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FreezeType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="FrequencyType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceivedType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GridExportType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GroupCycleType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GroupLoanInstallmentPolicy",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GroupTransferState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GroupTransferType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="GuaranteeComputationAmtComponent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="IDGenerationModule",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InstallmentRecoveryComponent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestCalcBalanceType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestCalcMethod",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestDaysCalcBase",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestRateCategory",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestRateType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InterestType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceCategory",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceSettlementState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LoanAgreementFormat",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LoanDeliquencyLevel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LoanDisbursementMode",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LoanDisbursementType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LoanState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LPODeliveryState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="LPOType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="MemberTransferState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationTimeOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="OfficerType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="OneOffFeeChargeModel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerBillState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ProductAccountingEvent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ProductGLAccount",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="QuickTransactionAmount",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ReportFilterCriteria",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ReportViewOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="RoundingOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="ShareRedemptionOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="StandingInstructionType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="StatementdateType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="SystemUserType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TellerDeclarationOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TillState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TillTransactionType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TillTransferType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionAccountType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionChargeEvent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDescription",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="Weekdays",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="WhoPayChargeOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowDocumentCategory",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowModule",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name="YesNo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
    ]
