# Generated by Django 5.0.14 on 2025-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SystemCode", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeId", models.CharField(max_length=4000)),
                ("CodeIdLanguage1", models.CharField(max_length=4000)),
                ("CodeIdLanguage2", models.CharField(max_length=4000)),
                ("CodeIdLanguage3", models.CharField(max_length=4000)),
            ],
        ),
    ]
