# Generated by Django 5.0.14 on 2025-06-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0006_alter_bankbranch_basecurrency"),
        ("SystemCode", "0003_currency_loanholidayhandling"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
