# Generated by Django 5.0.14 on 2025-08-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_remove_interestrate_rateid_interestrate_ratename'),
        ('SystemCode', '0005_interestrateid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestRateId',
        ),
    ]
